const ERROR_CODE_VALIDATION = 400;
const ERROR_CODE_CAST = 404;
const ERROR_CODE_SERVER = 500;
const ERROR_CODE_AUTH = 401;
const ERROR_CODE_DUPLICATE = 409;
const ERROR_CODE_RIGHTS = 403;

module.exports = {
  ERROR_CODE_VALIDATION,
  ERROR_CODE_CAST,
  ERROR_CODE_SERVER,
  ERROR_CODE_AUTH,
  ERROR_CODE_DUPLICATE,
  ERROR_CODE_RIGHTS,
};
